sonar.projectKey=Finfinder_DQN_Framework
sonar.organization=finfinder

sonar.sources=.
sonar.inclusions=**/*.py
sonar.exclusions=.venv/**,logs/**,metrics/**,**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
