sonar.projectKey=Finfinder_DQN_Framework
sonar.organization=finfinder

sonar.sources=.
sonar.inclusions=**/*.py
sonar.exclusions=.venv/**,logs/**,metrics/**,**/__pycache__/**

sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.coverage.exclusions=train.py,evaluate.py,play.py,tuning_test.py,version.py,utils/analyze.py,models/cnn_dqn_network.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
